### PR TITLE
Fix stream events kind snapshot

### PR DESCRIPTION
**Pull request by Profpatsch**
cc @symphorien 

- [ ] Amended the changelog in `release.nix` (see `release.nix` for instructions)

### CODE REVIEW

**Comment by Profpatsch** [comment]
TODO: create integration test to catch regressions.

**Review by symphorien — APPROVED** [review]
* lorri internal stream-event --kind snapshots works
* without --kind snapshot, it breaks. This is proably and existing problem resurfacing:
```commands
$  ./target/debug/lorri internal stream-events                
{"Completed":{"nix_file":"/home/symphorien/src/lorri/shell.nix","rooted_output_paths":{"shell_gc_root":"/home/symphorien/.cache/lorri/gc_roots/07d6e569120731e7ee9a3297613c71b7/gc_root/shell_gc_root"}}}
Mar 28 21:56:20.222 ERRO Message(R(Timeout(D(Millis(500)))))
```

**Comment by Profpatsch** [comment]
>     * without --kind snapshot, it breaks. This is proably and existing problem resurfacing:

Ah, I’m dumb. I should give this an infinite timeout.

**Comment by Profpatsch** [comment]
Now it works for me.

**Comment by Profpatsch** [comment]
I opened https://github.com/nix-community/lorri/issues/29 for the integration test

**Comment by theotherjimmy** [comment]
Confirmed, with this branch, stream-events works again.

**Comment by Profpatsch** [comment]
Cool, then let’s merge.

**Pull request merged**
