### PR TITLE
Improve gcroots check & fix CI

### PR DESCRIPTION
**Pull request by Profpatsch**
- [ ] Amended the changelog in `release.nix` (see `release.nix` for instructions)

### CODE REVIEW

**Comment by nyarly** [comment]
Looking into this I've found that the per-user gcroots have been essentially deprecated; something about a conflict with a non-root nix builder? The upshot does seem to be that the preference is for any manipulation of the nix gcroots be managed by nix tools or the nix daemon, which seems sensible to me.

Elsewhere, I was taking a stab at doing that with `nix build`, although I think `nix-store --realise` (if it works) would be a better choice until the `nix` command leaves "experimental."

**Comment by Profpatsch** [comment]
I don’t think it matters very much, nix upstream is a mess. I’d rather just improve what is there right now and worry about it when upstream decides to break us.

**Review by nyarly — APPROVED** [review]
Fine to proceed with this

**Comment by Profpatsch** [comment]
The one failing watcher test is annoying, I’m trying to figure out what’s going wrong there, but it’s gonna have to be a separate PR. So I’m merging this for now.

**Pull request merged**
