### PR TITLE
Fix logging & maintenance tasks

### PR DESCRIPTION
**Pull request by Profpatsch**
coming up

### CODE REVIEW

**Comment by Profpatsch** [comment]
Okay this turned out to be a bigger yak shave than expected.

I did a bit of maintenance, bumping nixpkgs and updating cargo packages, which lead to bumping our backwards compat version to 20.09.

This came from wanting to use the logger better, and noticing that e.g. the nix invocations weren’t even logged.

There’s also a fix that makes `-v` work again with a release build.

Plus I switched from carnix to cargo2nix, which was mostly a drop-in, but is actually a maintained tool.

**Comment by Profpatsch** [comment]
Oh, and the macos issue is separate, something or other has been broken there for a while, but afaik it’s unrelated to these changes.

**Comment by uri-canva** [comment]
The fix for the macOS issue in on nixpkgs master: https://github.com/NixOS/nixpkgs/commit/c9f0c6f115f4369b5047c3c3086518294541d0bf

**Comment by Profpatsch** [comment]
@uri-canva ah, nice, let’s see how we can integrate it into CI.

**Comment by Profpatsch** [comment]
Merging this for now, since it would just bit-rot otherwise

**Pull request merged**
