### PR TITLE
Vendor human panic

### LINKED ISSUE #21: vendor human-panic
human-panic is on very low maintenance, and given that it’s a super small crate, we might just vendor it in a single file instead.

I’d like to change the color to not use red, which will get rid of the ansi-terminal deps.

We should subtree it in.

### PR DESCRIPTION
**Pull request by Profpatsch**
Fixes #21 

I used `git subtree add --prefix vendor/human-panic https://github.com/rust-cli/human-panic master` to vendor the current master of the human-panic repo.

This should allow us to work on it like on upstream, while also being able to submit changes upstream, and potentially remove it again if upstream catches up.

### CODE REVIEW

**Review by sternenseemann — APPROVED** [review]
lgtm, not squashing is probably the wiser choice otherwise subtree tends to struggle with some stuff.

**Comment by Profpatsch** [comment]
People have a strange aversion to foreign commits in their trees. I don’t get it, but whatever floats people’s boats. :)

**Comment by Profpatsch** [comment]
Argh, clippy for some reason still uses a nightly version; I thought we had that fixed, but maybe it fetches its database from some URL‽

**Comment by Profpatsch** [comment]
Anyway, we can start modifying human-panic now.

**Pull request merged**
