### PR TITLE
Better flake error msg

### PR DESCRIPTION
**Pull request by gilescope**
While we don't have native support for flakes yet this PR suggests the workaround suggested in https://github.com/target/lorri/issues/460 if and only if there's no shell.nix and there's a flake.nix found.

I thought about creating the file automatically but I think just suggesting it is nicer.

### CODE REVIEW

**Review by nyarly — CHANGES_REQUESTED** [review]
I think this is 100% better than the nothing we have now. Could you update against canon, please, and I'd be inclined to merge.

One thing I note (and post-merge I'd open an issue for this): using this shim, lorri doesn't track the flake.nix or flake.lock. Until lorri supports flakes natively, a shim that somehow registered them would be amazing.

If you have immediate ideas about that, feel free to incorporate them

**Comment by nyarly** [comment]
@gilescope Are you still inclined to get this merged?

**Comment by gilescope** [comment]
Back from holidays. Sure, have updated it @nyarly - let me know if there's any other changes needed before merge.

**Comment by nyarly** [comment]
Thanks, @gilescope !

**Pull request merged**
